on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, macos-15, macos-14, macos-13 ]
        hippomocks: [ build/hippomocks-master, build/hippomocks-colobot ]
    steps:
    - uses: actions/checkout@v4
    - run: cmake -S . -B build
    - run: make -C build
    - run: ${{ matrix.hippomocks }}
